import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout
({
	children,
}: Readonly<
{
	children: React.ReactNode;
}>)
{
	return (
		<html lang="en">
			<body className="bg-linear-to-b from-[#0f1726] to-[#14202f]">{children}</body>
		</html>
	);
}
